---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: oozie/r2c-bento
params: []
inputs:
  - name: code-repo
  - name: bento-config
  - name: bento-baseline
outputs:
  - name: bento-baseline
run:
  path: /bin/bash
  args:
  - -c
  - |
    set -eux
    (
      cd code-repo
      git config --global user.name "oozie"
      git config --global user.email "oozie@ci"
      bento init
    )
    cp bento-baseline/bento-baseline.yml code-repo/.bento-baseline.yml
    cp bento-config/bento.yml code-repo/.bento.yml
    (
      cd code-repo
      #  If bento-baseline is empty, establish baseline
      if [ ! -s .bento-baseline.yml ]; then
        bento reset
      # Otherwise do the checking
      else
        bento check
      fi
    )
    cp code-repo/.bento-baseline.yml bento-baseline/bento-baseline.yml
