---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: oozie/r2c-bento
params: []
inputs:
  - name: code-repo
run:
  path: /bin/bash
  args:
  - -c
  - |
    (
      cd code-repo
      bento setup
      bento check
    )

