---
resources:
- name: code-repo
  type: git
  source:
    uri: git@github.com:oozie/protobento.git
    private_key: ((ci.bento/Notes/repo_key))
    branch: master

- name: bento-baseline
  type: s3
  source:
    bucket: ((ci.bento/Notes/aws_bucket))
    versioned_file: bento-baseline.yml
    access_key_id: ((ci.bento/Notes/aws_access))
    secret_access_key: ((ci.bento/Notes/aws_secret))
    region_name: ((ci.bento/Notes/aws_region))

- name: bento-config
  type: s3
  source:
    bucket: ((ci.bento/Notes/aws_bucket))
    versioned_file: bento.yml
    access_key_id: ((ci.bento/Notes/aws_access))
    secret_access_key: ((ci.bento/Notes/aws_secret))
    region_name: ((ci.bento/Notes/aws_region))

jobs:
- name: bento-check
  plan:
  - get: code-repo
    trigger: true
  - get: bento-config
  - get: bento-baseline
  - task: run-bento
    file: code-repo/ci/tasks/bento.yml
  - put: bento-baseline
    params:
      file: bento-baseline/bento-baseline.yml

- name: deploy
  plan:
  - get: code-repo
    trigger: true
    passed: [ bento-check ]
  - task: do-deployment
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oozie/r2c-bento
      run:
        path: bash
        args:
        - -c
        - |
          echo deploying...


- name: reset-baseline
  plan:
  - task: zero-out-baseline
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: oozie/r2c-bento
      outputs:
        - name: bento-baseline
      run:
        path: bash
        args:
        - -c
        - |
          echo -n > bento-baseline/bento-baseline.yml
  - put: bento-baseline
    params:
      file: bento-baseline/bento-baseline.yml
